[custom]
enable_rule_generator=true
overwrite_original_rules=true

;================ Ruleset ================

ruleset=🏠 局域网直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list

; 广告过滤 Full
ruleset=⛔️ 广告过滤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=⛔️ 广告过滤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=⛔️ 广告过滤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=⛔️ 广告过滤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list

; 国内直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list

; 核心分流
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list

; 常规代理
ruleset=🚀 节点选择,https://raw.githubusercontent.com/qichiyuhub/rule/master/ProxyLite.list

; 最终兜底
ruleset=🐟 漏网之鱼,[]FINAL


;================ Proxy Groups ================

custom_proxy_group=🚀 节点选择`select`[]🎥 流媒体节点`[]🤖 AI节点`[]🏠 家宽节点`[]💸 便宜节点`[]🐸 手动切换`[]DIRECT

custom_proxy_group=🎥 流媒体节点`select`流媒体解锁|Netflix|NETFLIX|NF|奈飞|Media|media

custom_proxy_group=🤖 AI节点`select`AI|OpenAI|ChatGPT|Claude|Gemini

custom_proxy_group=🏠 家宽节点`select`家宽|家庭|住宅|Residential|residential

custom_proxy_group=💸 便宜节点`select`0.1x|0.1X|0.5x|0.5X|0.5倍

custom_proxy_group=🐸 手动切换`select`.*

custom_proxy_group=🏠 局域网直连`select`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=⛔️ 广告过滤`select`[]REJECT`[]DIRECT

; 业务分流
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🤖 AI节点`[]🐸 手动切换

custom_proxy_group=🎥 Netflix`select`[]🎥 流媒体节点`[]🚀 节点选择`[]🐸 手动切换

custom_proxy_group=📹 YouTube`select`[]🎥 流媒体节点`[]🚀 节点选择`[]🐸 手动切换

custom_proxy_group=🤖 AI服务`select`[]🤖 AI节点`[]🎥 流媒体节点`[]🚀 节点选择`[]🐸 手动切换

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]🐸 手动切换
